### ISSUE TITLE
additional ip adresses for eu central

### ISSUE THREAD

**Issue by tharoscs** [Disquse/PUBGServersPing#1]
eu-central-1 - 52.57.67.93
eu-central-1 - 52.28.34.137	
eu-central-1 - 52.57.67.93	
eu-central-1 - 52.57.169.116	
eu-central-1 - 52.59.68.3	
eu-central-1 - 52.57.168.131	
eu-central-1 - 35.157.61.251	
eu-central-1 - 52.57.241.171
eu-central-1 - 52.29.125.80		
eu-central-1 - 52.58.95.114
eu-central-1 - 35.157.61.4

**Comment by Disquse** [comment]
Added. Thanks!
