### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by godstick0517** [Disquse/PUBGServersPing#12]
Hello,
Thanks for your project, and it seems that the pubg is hosted on Microsoft Azure now, so could you update some information on the website if you are free?
Thanks again.

**Comment by Disquse** [comment]
Nah. Sorry. I didn't have time for this. There is alot what I should update for this website. But anyway.

> Main problem of PUBG servers is not ping. Game servers just overloaded, that's why you lagging. You can try play on another servers. Big ping is much smaller problem that overloaded servers. Unfortunately, we can't check servers load...

**Comment by delidolu1adam** [comment]
Hello, thanks for this website. Turkish language translation is completed.Please, download and added to your website.

Download: https://drive.google.com/drive/folders/0B_cukfssvcCpX3JWc2pUWjZtZmc?usp=sharing

**Comment by Disquse** [comment]
I guess now this can be closed as I described my position about this issue in "About" section after refactor (#15) happened.
