### ISSUE TITLE
Server IP address

### ISSUE THREAD

**Issue by alifasad** [Disquse/PUBGServersPing#20]
On the old interface you had server Ip addresses but On new interface that is missing please add that option as I need the addresses to optimize my latency. If you don't want to make it public please send me a mail.
Md asadur rahman
asaduralif@gmail.com

**Comment by Disquse** [comment]
It was removed because a current IP list is outdated. However, you can see all of them in this file: https://github.com/Disquse/PUBGServersPing/blob/master/src/configs/servers.ts
