### ISSUE TITLE
Server:China (Beijing)？

### ISSUE THREAD

**Issue by RunTuu** [Disquse/PUBGServersPing#5]
What does that mean?
Do you know anything about Chinese server?

**Comment by cryschao** [comment]
@RunTuu 大兄弟，5月份这哥们儿第一个版本就已经提交了北京的节点，看来是，，，乌龙。

**Comment by RunTuu** [comment]
@cryschao 那就很僵硬了，这两天还被国内媒体报导了一遍，江来出了偏差。。

**Comment by majesty17** [comment]
我尼玛还一本正经的提交了这个网页的中文版。。。

**Comment by Disquse** [comment]
This means that PUBG probably have server in China (Asia)?

**Comment by majesty17** [comment]
@Disquse 
we know nothing about China server. 
as we known before,  the only server in Asia locates at Korea, until people saw some evidence shown at your website.

**Comment by Disquse** [comment]
@majesty17 
As I writed in "Help" section, site uses AWS servers as endpoint for measuring ping. When I created first version of site, I not worried about asia and america at all. Will be awesome if someone take care about the IPs. Unfortunately, I don't have enough time for researching.

**Comment by imtyz001** [comment]
@majesty17 在 http://pubg.disquse.ru/ 的List里列出了PUBG用的服务器列表，网页上的PING应该只是检测到AWS服务器的延迟，PUBG没有在北京的AWS服务器提供服务
