### ISSUE TITLE
Do You need Simplified Chinese ?

### ISSUE THREAD

**Issue by FastChen** [Disquse/PUBGServersPing#9]
I uploaded here
I don't know how to use Github XD
https://github.com/FastChen/PUBGServersPingLang/blob/master/cn.php

**Comment by Disquse** [comment]
Check this out: https://help.github.com/articles/creating-a-pull-request/
If it's still understable for you I can merge it myself

**Comment by FastChen** [comment]
OK, I'll try…
Not very useful github
